# This file was generated by GoReleaser. DO NOT EDIT.
class Gadb < Formula
  desc "Golang ADB wrapper providing all ADB features and more"
  homepage "https://github.com/esafirm/homebrew-tap"
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/esafirm/gadb/releases/download/1.1.0/gadb_1.1.0_Darwin_x86_64.tar.gz"
    sha256 "84a77fa6ddcca2f20e0e6f29df27e9bb0ff48188a547ad56c058882926b70536"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/esafirm/gadb/releases/download/1.1.0/gadb_1.1.0_Linux_x86_64.tar.gz"
      sha256 "eddc6448dcf3b83f9c396ad7d6507d69445eab901c184200347d7436a3874bbb"
    end
  end

  def install
    bin.install "gadb"
  end
end
