# This file was generated by GoReleaser. DO NOT EDIT.
class Gadb < Formula
  desc ""
  homepage "https://github.com/esafirm/homebrew-tap"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/esafirm/gadb/releases/download/1.0.1/gadb_1.0.1_Darwin_x86_64.tar.gz"
    sha256 "53f8ac7dc0c7b2ae7c83fe17513a032dc8e69393c45fe132b5c14d01d124552e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/esafirm/gadb/releases/download/1.0.1/gadb_1.0.1_Linux_x86_64.tar.gz"
      sha256 "fbad760645ab3a1b5e395ff7c02aef7032245574834941630d5a926384853f81"
    end
  end

  def install
    bin.install "gadb"
  end
end
