# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Okmock < Formula
  desc "HTTP(s) request mocker for Android (OkHttp) and Flutter (Dio)"
  homepage "https://github.com/esafirm/homebrew-tap"
  version "1.1.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/esafirm/okmock/releases/download/1.1.0/okmock_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "ad7791eb289cea8fb9022c1f8cd8a34a5c83e72576f6008cea4d5066d894cdba"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/esafirm/okmock/releases/download/1.1.0/okmock_1.1.0_Linux_x86_64.tar.gz"
      sha256 "41a36f365b9762b6c86792a71742e89bf09e11e402d62a0da4b83a851d29def6"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/esafirm/okmock/releases/download/1.1.0/okmock_1.1.0_Linux_arm64.tar.gz"
      sha256 "90b8ed50717266bbd8e7d9afec5166de8bfda3525a8a7eb0b88caf234f273c7f"
    end
  end

  def install
    bin.install "okmock"
  end
end
